package bobzone.hrf.humanresource.Model


/**
 * Created by davidwibisono on 3/11/18.
 */
open class UserSettings {

    private object Holder { val INSTANCE = UserSettings() }

    companion object {
        val instance: UserSettings by lazy { Holder.INSTANCE }
    }

    //LEAVE APPLICATION
    val LEAVE_APPLICATION_OPEN = "LEAVE_APPLICATION_OPEN"
    val LEAVE_APPLICATION_APPROVED = "LEAVE_APPLICATION_APPROVED"
    val LEAVE_APPLICATION_REJECTED = "LEAVE_APPLICATION_REJECTED"

    //SALES ORDER ACTIVE
    val SALES_ORDER_ACTIVE_TO_DELIVER_AND_BILL_TOGGLE = "SALES_ORDER_ACTIVE_TO_DELIVER_AND_BILL_TOGGLE"
    val SALES_ORDER_ACTIVE_TO_BILL_TOGGLE = "SALES_ORDER_ACTIVE_TO_BILL_TOGGLE"
    val SALES_ORDER_ACTIVE_TO_DELIVER_TOGGLE = "SALES_ORDER_ACTIVE_TO_DELIVER_TOGGLE"

    //INVOICE
    val INVOICE_OVERDUE = "INVOICE_OVERDUE"
    val INVOICE_UNPAID = "INVOICE_UNPAID"

    //LEAD
    val LEAD_LEAD = "LEAD_LEAD"
    val LEAD_OPEN = "LEAD_OPEN"
    val LEAD_REPLIED = "LEAD_REPLIED"
    val LEAD_OPPORTUNITY = "LEAD_OPPORTUNITY"
    val LEAD_INTERESTED = "LEAD_INTERESTED"
    val LEAD_QUOTATION = "LEAD_QUOTATION"
    val LEAD_LOST_QUOTATION = "LEAD_LOST_QUOTATION"
    val LEAD_CONVERTED = "LEAD_CONVERTED"
    val LEAD_DO_NOT_CONTACT = "LEAD_DO_NOT_CONTACT"


}